### ISSUE TITLE
Login na stisknutí klávesy enter při jediném zobrazeném IdP.

### ISSUE THREAD

**Issue by xchvojkajan** [CESNET/wayf#11]
Při jediném zobrazeném IdP by po stisknutí klávesy enter mělo dojít k přesměrování na toto IdP.

**Comment by xchvojkajan** [comment]
Resolved

**Comment by JanOppolzer** [comment]
Mně to tedy (Linux, Firefox 44.0) nefunguje. Mám-li v seznamu pouze CESNET, tak na něj stejně musím kliknout myší. :(

**Comment by JanOppolzer** [comment]
Ani v Chrome 48.0.2564.116 na Linuxu to nefunguje.

**Comment by xpolish** [comment]
Ahoj,

   zkus to vic popsat. Vlezu na eduid.cz, dam jiny ucet, dam vyhledat
cesnet, zustane ve vypisu pouze cesnet, bouchnu do entru a mam ho tam.
Jde i o enter v ulozenych IdP?

     Pavel

**Comment by JanOppolzer** [comment]
Při vyhledání IdP to funguje, ale pokud mám zapamatované IdP (přihlášení -> zobrazí se pouze zapamatované IdP -> zmáčknu Enter), pak se nic nestane.

Původně jsem se špatně vyjádřil, moje chyba, omlouvám se.

**Comment by xpolish** [comment]
Testni to na https://dsa-test.eduid.cz/wayf.php?filter=eyJ2ZXIiOiIyIiwiYWxsb3dGZWVkcyI6eyJlZHVJRC5jeiI6e30sImVkdUdBSU4iOnt9LCJTb2NpYWwiOnt9LCJTdGFuZGFsb25lSWRQIjp7fX0sImFsbG93SG9zdGVsIjp0cnVlLCJhbGxvd0hvc3RlbFJlZyI6ZmFsc2V9&entityID=https%3A%2F%2Fattributes.eduid.cz%2Fshibboleth&return=https%3A%2F%2Fattributes.eduid.cz%2FShibboleth.sso%2FLogin%3FSAMLDS%3D1%26target%3Dss%253Amem%253A869ccd09383d738b23c2e30dbba984e26ee17d66ac2fa697292a86bc700d8710
