### ISSUE TITLE
Přidat GitHub a OrcID do Social IDP

### ISSUE THREAD

**Issue by zlamalp** [CESNET/wayf#19]
Ahoj,

@martin-kuba přidal podporu pro GitHub a OrcID do CESNETího extIdP. Můžete je prosím přidat do WAYFu mezi sociální identity, aby je uživatelé mohli používat ? Díky.

Odkazy jsou:

https://extidp.cesnet.cz/idp/shibboleth&authnContextClassRef=urn:cesnet:extidp:authn:github
https://extidp.cesnet.cz/idp/shibboleth&authnContextClassRef=urn:cesnet:extidp:authn:orcid

**Comment by semik** [comment]
Ahoj,
pridal jsem to tam, ale chova se to docela blbe. Pote co si na WAYFu zvolim jakykoliv socialni IdP. Tak se zobrazi znova dalsi WAYF. Ted uz jen se socilanima IdP, ted uz na https://extidp.cesnet.cz/idp/AuthnEngine  To mi prijde dost divny.

Semik

**Comment by zlamalp** [comment]
Ahoj, 

moc díky za přidání. Konečně si mohu oddělat hack, který mi je přidával ručně :-)

Přesměruje to na další wayf proto, že máte u všech social IdP špatně URL (entity ID). Pokud vím, @tauceti2 to hlásil jinou cestou už dříve. Máte tam ``&amp;`` a má tam být ``&``. Protože za vším je jedno IdP, které jen dělá proxy podle parametru v URL. Ten se ale kvůli špatnému zápisu nikdy nevyhodnotí a tak zobrazí vlastní wayf.

Jinak ještě generátor filtru pro wayf generuje špatný filtr (pro social IdP). Hlásil nám to jeden admin, měl vám napsat na eduid-admin, ale nevím jestli to udělal. Takže pokud bys k tomu chtěl detaily, mohu je poslat na mail.

Pavel

**Comment by semik** [comment]
Ahoj,

zda se ze tohle jsem solidne zpackal. Nejen ze nam dneska GitHub a OrcID vypadli pri odstranovani mojeID ale tvoji reakci z Jan 28, 2016 jsem necetl. Mozna protoze tohle nebylo nikomu prirazeno? 

Ten &amp; je fakt nahovno... zkousel jsem ho prepsat jako &#x26; ale to nikam nevede. Metadata se zpracovavaji xsltproc a ten generuje zase xml, no sice json ale on si mysli ze je to xml. Ale kvuli ascii vystupu uz tam mam dozpracovani v perlu, takze sem to zpatlal taky v perlu. https://github.com/CESNET/wayf/commit/7e8f51a7e72783aa086ebf98f51725117f3e3594

Loga GitHub a OrcID vyresime zitra. Je ale vyreseny ten druhy zretezeny WAYF.

**Comment by zlamalp** [comment]
Ahoj @semik, nic se neděje a díky za opravu.

**Comment by semik** [comment]
Uz tam jsou i loga. Takze snad na druhy pokus vyreseno.
