### ISSUE TITLE
Vyhledávání na základě domény organizace

### ISSUE THREAD

**Issue by JanOppolzer** [CESNET/wayf#33]
Bylo by užitečné, aby šlo vyhledávat organizace na základě **domény druhého řádu** (_Univerzita Karlova_ / _Charles university_ = `cuni.cz`).

Otázkou je, jak by to ovlivnilo rychlost zobrazení WAYFu.

Klíč by mohl být `o`. Možná by stálo za zvážení, aby se i ostatní klíče přejmenovaly (zkrátily) a případně zauvažovat i nad slovníkem např. pro kategorie entit, aby se výsledný JSON soubor zmenšil.

**Comment by xpolish** [comment]
Pridano vyhledavani podle entityID z metadat.
